/**
 * Every Sarom stockist supplied directly by the client (CUSTOMER DETAILS.xlsx,
 * Sept 2026) — 150 of them across 14 states, kept verbatim apart from
 * whitespace and punctuation tidying. Nothing invented, nothing added.
 *
 * This REPLACES the 195-store list scraped from sarom.info/store-locator.php:
 * that source had no store names and no coordinates, only a state and a
 * free-text address. This one carries a real customer/store name, a
 * structured city and a 6-digit pincode for every row, so the panel and
 * directions are both more precise. The scraped list is not merged in
 * alongside it — the two were never reconciled against each other and might
 * double-count the same physical store under different names.
 */

export type Store = { name: string; address: string; city: string; state: string; pincode: number };

export const STORES: Store[] = [
  { name: "PRAKASH FINE FAB PRIVATE LIMITED", address: "NO 112 and 112/1, Ground, 1st and 2nd Floor, Lalbagh Fort Road, Mavali, Mavalli, Bengaluru, Bengaluru Urban", city: "BANGALORE", state: "KARNATAKA", pincode: 560004 },
  { name: "M/S. NIRMAL HANDLOOM HOUSE PVT LTD.", address: "3/4 FURNITURE BLOCK, , KEERTI NAGAR", city: "DELHI", state: "DELHI", pincode: 110015 },
  { name: "KRISHA ENTERPRISE (NEW)", address: "A14, BANSHIDHAR SOCIETY, CHANDRA NAGAR, OPP.BANSHIDHAR GARDEN, PALDI", city: "AHMEDABAD", state: "GUJARAT", pincode: 380007 },
  { name: "CALIBER ENTERPRISES", address: "BESIDE SURYA TOWERS, , REDDY HOSTEL SHOPPING COMPLEX, TILAK ROAD", city: "HYDERABAD", state: "TELANGANA", pincode: 500001 },
  { name: "SHIRO HOME DECOR - NEW", address: "Unit No C-9, 27 Acre, Kothari Warehouse, Tikuji Ni Wadi Road, omnitek Road, Tikuji Ni Wadi", city: "THANE", state: "MAHARASHTRA", pincode: 400607 },
  { name: "SHREENATHJI CLOTH TRADERS - RAJKOT", address: "30, PRAHLAD PLOT CORNER, , DIGVIJAY ROAD", city: "RAJKOT", state: "GUJARAT", pincode: 360001 },
  { name: "ONE UP FURNISHING", address: "GROUND FLOOR, UDAY BHANU APARTMENT, M.G.ROAD, GHATKOPAR E", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400077 },
  { name: "PRAKASH FOAM MART LLP", address: "ground Second and 3rd Floor 108 Lalbagh, Main Road Mavalli Bengaluru Bengaluru Urban Karnataka", city: "BANGALORE", state: "KARNATAKA", pincode: 560004 },
  { name: "BHAVANI FURNISHING FABRICS", address: "17-1-382/K/5/A, BEHIND ICICI BANK, , VISHNUPURI COLONY, CHAMPAPET", city: "HYDERABAD", state: "TELANGANA", pincode: 500079 },
  { name: "RIGHT CHOICE", address: "SHOP NO. 11, DUBAS MARKET, , OPP. MANGALDAS MARKET", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400002 },
  { name: "B.F.FASHIONS PVT. LTD.", address: "CRYSTAL CLASSIC, NEXT TO GOLDEN TOBACCO, , S.V. ROAD", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400056 },
  { name: "NEPTUNE HOUSE", address: "41, SHRIMATI SOCIETY, NEAR NAVRANGPURA RAILWAY CROSSING", city: "AHMEDABAD", state: "GUJARAT", pincode: 380009 },
  { name: "AKESHA FURNISHING - MULUND", address: "SHOP NO. 3 SHIDHARTH TOWER, , PURUSHOTTAM KHERAJ ROAD", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400080 },
  { name: "SHA SURAJMULL MAGRAJ & CO.", address: "NO. 15, KOTHARI BLDG., # 1, , D.S.LANE, CHICK PET.", city: "BANGALORE", state: "KARNATAKA", pincode: 560053 },
  { name: "FLOATING WALLS PVT LTD", address: "# 20, Sarjapura Main Road Jakkasandra, 1st Block Koramangala.", city: "BANGALORE", state: "KARNATAKA", pincode: 560034 },
  { name: "DECOTEX", address: "GHOD BUNDER ROAD, , MANPADA", city: "THANE", state: "MAHARASHTRA", pincode: 400607 },
  { name: "BELLA FURNISHING", address: "SHOP NO 1, JAY COMPLEX, , ANAND MAHAL ROAD, ADAJAN", city: "SURAT", state: "GUJARAT", pincode: 395009 },
  { name: "LALCHAND HASSANAND", address: "SHOP NO.77, M.T.CLOTH MARKET, FREEGANJ", city: "INDORE", state: "MADHYA PRADESH", pincode: 452002 },
  { name: "PAREKH & CO.", address: "BROADWAY SHOPPING CENTRE, , DADAR T.T", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400014 },
  { name: "HILLARYS WINDOW COVERINGS INDIA PRIVATE LIMITED", address: "Ground Floor, 107 & 107A, Prestige Atrium, Central Street, Shabbirs Furnishing Centre, Civil Station", city: "BANGALORE", state: "KARNATAKA", pincode: 560001 },
  { name: "DESIGN WALLS", address: "3RD FLOOR, MSR CAPITAL, BESIDE INDIAN OIL PETROL PUMP, NEAR MIYAPUR METRO STATION", city: "HYDERABAD", state: "TELANGANA", pincode: 500049 },
  { name: "AKESHA - THANE", address: "GR. FLOOR, SHOP NO.2, SHIVANTA BUILDING, ALMEDA ROAD, INFRONT OF TMC OFFICE", city: "THANE", state: "MAHARASHTRA", pincode: 400601 },
  { name: "JAYDURGA FURNISHINGS PRIVATE LIMITED", address: "GROUND FLOOR 1 10 32 TO 37D003, D BLOCK, WELKKIN PARK, PARKASH NAGAR", city: "HYDERABAD", state: "TELANGANA", pincode: 500016 },
  { name: "NAVEEN BHARAT FURNISHING P. LTD.", address: "S C O 4 & 5, NR. NEHRU SIDDHANTH KENDRA, PAKHWAL ROAD", city: "LUDHIANA", state: "PUNJAB", pincode: 141001 },
  { name: "GALLERY ONE", address: "SHOP # 5, DIVINE COMPLEX, ROAD NO - 12, BANJARA HILLS", city: "HYDERABAD", state: "TELANGANA", pincode: 500034 },
  { name: "KUSHAL DECOR", address: "No. 4, 1st FLOOR, 3R PLAZA, 100 FEET ROAD, INDIRANAGAR, HAL 2ND A STAGE", city: "BANGALORE", state: "KARNATAKA", pincode: 560038 },
  { name: "G.S. DECOR", address: "401, GOYAL NAGAR, , RING ROAD BENGALLI SQUARE.", city: "INDORE", state: "MADHYA PRADESH", pincode: 452001 },
  { name: "SHRI GRAH SHOBHA - INDORE", address: "4, VIJAY NAGAR, IN FRONT OF MANGAL CITY, AB ROAD", city: "INDORE", state: "MADHYA PRADESH", pincode: 452001 },
  { name: "GURUKRUPA FURNISHING - NASHIK", address: "\"GEETAI\" BUNGLOW, , BEHIND HOTEL DWARKA, NEAR AGRA ROAD", city: "NASHIK", state: "MAHARASHTRA", pincode: 422011 },
  { name: "MANSAROVER FURNISHING PVT. LTD.", address: "NEAR RED LIGHT CHOWK, GT ROAD", city: "PANIPAT", state: "HARYANA", pincode: 132103 },
  { name: "LUXUR & LAVISH", address: "MOTILAL NAGAR, 1 - 270/2141, NEW LINK CHS, , LINK ROAD, MUMBAI SUBURBAN, GOREGAON WEST", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400104 },
  { name: "FABIN FNF", address: "B/25, B.M.C COLONY, NEAR CHAWHAN TOWER, OPP.METRO PILLAR NO.482/5, NEW LINK ROAD, GOREGAON WEST", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400104 },
  { name: "COLORS FURNISHINGS STUDIO - DELHI", address: "92, FIRST FLOOR, ADHCHINI, SRI AUROBINDO MARG", city: "DELHI", state: "DELHI", pincode: 110017 },
  { name: "KAPAAS HOME FURNISHING PVT. LTD.", address: "350, M. G. ROAD, , METRO STATION", city: "DELHI", state: "DELHI", pincode: 110030 },
  { name: "AMBEY FURNISHING", address: "H NO. 8-2-272/18, FIRST FLOOR, SRI RANGA TOWERS, OPP.LUMBINI MALL, ROAD NO.2, BANJARA HILLS", city: "HYDERABAD", state: "TELANGANA", pincode: 500034 },
  { name: "RUN RARE BUYING SERVICES", address: "212-A, GROUND FLOOR, SHAHPUR JAT", city: "DELHI", state: "DELHI", pincode: 110049 },
  { name: "RAINBOW", address: "UL-15 DEVDARSHAN TOWER, OPP. MANEKBAUG HALL, AMBAWADI.", city: "AHMEDABAD", state: "GUJARAT", pincode: 382443 },
  { name: "R K FURNISHINGS PRIVATE LIMITED - GURUGRAM", address: "21, 22, 23 AND 24, IREO CITY CENTRAL, GOLF COURSE EXTENSION ROAD", city: "GURGAON", state: "HARYANA", pincode: 122101 },
  { name: "DRAPE SHOPPE SURAT", address: "J.K. CHAMBERS, BHAGATALAO, PANI NI BHINT.", city: "SURAT", state: "GUJARAT", pincode: 395003 },
  { name: "FOAM PALACE TRADING (INDIA) PVT. LTD.", address: "SHOP NO. 4 / 5, JAIN CHAMBERS, 577, S. V. ROAD., BANDRA (W)", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400050 },
  { name: "FURNISHING TOUCH", address: "AC 114, 4TH AVENUE, SHANTI COLONY., ANNA NAGAR", city: "CHENNAI", state: "TAMIL NADU", pincode: 600040 },
  { name: "PATEL TRADING CO.- (BHAVNAGAR)", address: "DHOBI STREET, OPP DAVE SWEET, , M.G ROAD.", city: "BHAVNAGAR", state: "GUJARAT", pincode: 364001 },
  { name: "LILA FURNISHINGS PVT LTD", address: "INDIA HOUSE KEMPS CORNER, , CUMBALLA HILL", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400026 },
  { name: "THE HOME COLLECTION", address: "1ST FLOOR, 3724-A STREET NO.9, NARANG COLONY, NEW DELHI NORTH WEST", city: "DELHI", state: "DELHI", pincode: 110035 },
  { name: "DRAPES AVENUE - BANGALORE", address: "RAMANASHREE CHAMBERS NO.37, LADY CURZON ROAD.", city: "BANGALORE", state: "KARNATAKA", pincode: 560001 },
  { name: "HIGH STREET", address: "HOUSE NO 1/92 PLOT NO 92, RIGHT PORTION BASEMENT, AND GROUND FLOOR, WHS BLK-1, KIRTI NAGAR", city: "DELHI", state: "DELHI", pincode: 110015 },
  { name: "STUDIO RK - DELHI - NEW", address: "A-19, FIRST SECOND THIRD, KIRTI NAGAR, NEW DELHI", city: "DELHI", state: "DELHI", pincode: 110015 },
  { name: "OM SAI DECOR", address: "SHOP 1 & 5, BHR PLAZA, , BALIRAM PETH", city: "JALGAON", state: "MAHARASHTRA", pincode: 425001 },
  { name: "S H RETAIL PRIVATE LIMITED", address: "PLOT NO 85, UDYOG VIHAR, PHASE 1, GURGAON", city: "GURGAON", state: "HARYANA", pincode: 122016 },
  { name: "PETALS INDIA", address: "PLOT NO. - 34, , INDUSTRY AREA PHASE 2", city: "PANCHKULA", state: "HARYANA", pincode: 134109 },
  { name: "HANDLOOM HERITAGE", address: "139-140, AMBALA WHOLESALE COMPLEX, NEAR KALKA CHOWK, AMBALA CITY", city: "AMBALA", state: "HARYANA", pincode: 134003 },
  { name: "RADHA FURNISHING", address: "NO.42, , DICKENSON ROAD", city: "BANGALORE", state: "KARNATAKA", pincode: 560042 },
  { name: "CASA LUJO HOME LUXURY LLP", address: "PLOT NO-14/3, BASEMENT BELOW, SAMSUNG & VOLTAS SHOWROOM, MAHARAJPUR, Faridabad", city: "FARIDABAD", state: "HARYANA", pincode: 121003 },
  { name: "SIRSEJ INTERIOR PRIVATE LIMITED", address: "GROUND FLOOR, PLOT NO 12F/1, GIRDHAR IND ESTATE, UDHNA MAGDALLA ROAD, SURAT", city: "SURAT", state: "GUJARAT", pincode: 395017 },
  { name: "KOTHARI HOME FURNISHING", address: "814/1A, OPP. HIGH SCHOOL GROUND, P B ROAD, , DAVANAGERE", city: "DAVANGRE", state: "KARNATAKA", pincode: 577002 },
  { name: "FURNISH AND SHADE", address: "B-202, Mansarover Garden, Kirti Nagar, New Delhi, West Delhi", city: "DELHI", state: "DELHI", pincode: 110015 },
  { name: "RAJU FURNISHING - INDORE", address: "SHOP NO.16-18, GAUTAMPURA MAIN ROAD, NEAR PANDRINATH", city: "INDORE", state: "MADHYA PRADESH", pincode: 452007 },
  { name: "PURPLE PATCH STUDIO", address: "23/E, LAXMI INDUSTRIAL ESTATE, , NEW LINK ROAD, ANDHERI (WEST)", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400053 },
  { name: "DREAM HOMES", address: "184 E, SHANTI NAGAR, , MODEL TOWN, PANIPAT", city: "PANIPAT", state: "HARYANA", pincode: 132103 },
  { name: "DREAMS FURNISHINGS", address: "4 2, SF, WHS, KIRTI NAGAR, KIRTI NAGAR WEST DELHI", city: "DELHI", state: "DELHI", pincode: 110015 },
  { name: "INTERGO FURNISHING - KERALA", address: "GOLDEN PALACE VIEWS, OPP.INCOME TAX OFFICE, , AMBALAMUKKU ROAD, KOWDIAR P.O", city: "TRIVENDRUM", state: "KERALA", pincode: 695003 },
  { name: "KDL - VADODARA", address: "1, 2, 3, 4, 5, OM PARK SOCIETY, NEAR KALASH CIRCLE, OPP.PANERI SHOWROOM, AKOTA", city: "VADODARA", state: "GUJARAT", pincode: 390020 },
  { name: "KHANDELWAL DRAPE SHOPPE", address: "77, EMERALD BLDG., NR. GOVARDHAN NATHJI HAVELI, B. P. C. ROAD, ALKAPURI", city: "VADODARA", state: "GUJARAT", pincode: 390020 },
  { name: "GOLDEN DRAPE VAISHALI", address: "328-329, NEMI SAGAR COLONY, MAIN QUEENS ROAD, VAISHALI NAGAR.", city: "JAIPUR", state: "RAJASTHAN", pincode: 302021 },
  { name: "NOVELTY FURNISHING- BANDRA", address: "249, NAVALKUNJ LINKING ROAD OPP. NATIONAL COLLEGE LINKING ROAD, BANDRA (W)", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400050 },
  { name: "SUKRITI FURNISHINGS & DESIGN STUDIO", address: "S C O 841, , N A C MANIMAJRA", city: "CHANDIGARH", state: "CHANDIGARH", pincode: 160101 },
  { name: "ARAMBH FURNISHING PVT. LTD.", address: "B-26, RDC CHAWLA TANDURI, RAJ NAGAR", city: "GHAZIABAD", state: "UTTAR PRADESH", pincode: 201002 },
  { name: "STUDIO RION", address: "PLOT-NO-1262, ROAD#36, NEAR CHECK POST, JUBILEE HILLS, HYDERABAD", city: "HYDERABAD", state: "TELANGANA", pincode: 500034 },
  { name: "CREATIVE FURNISHING STUDIO", address: "D.NO.53-17-20, FIRST FLOOR, BESIDE AUTOMOTIVE MANUFACTURE LTD, MADDILAPALEM", city: "VISHAKHAPATNAM", state: "ANDHRA PRADESH", pincode: 530022 },
  { name: "RESHMA FURNISHING & MATTRESSES", address: "SHOP NO.5, NR. AMBOLI NAKA SIGNAL, S. V. ROAD, ANDHERI - WEST", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400058 },
  { name: "DECOR INDIA FURNISHINGS", address: "FIRST FLOOR, HUB 66, OPPOSITE ANSAL ESSENCIA, SEC 66", city: "GURGAON", state: "HARYANA", pincode: 122018 },
  { name: "AWARD FURNISHING", address: "833, QUEENS ROAD, S. P. MUKHRJEE MARG, -", city: "DELHI", state: "DELHI", pincode: 110006 },
  { name: "MO DESIGNS PRIVATE LIMITED", address: "A-6 SUSHANT LOK-1, MG ROAD, GURGAON", city: "GURGAON", state: "HARYANA", pincode: 122002 },
  { name: "N P PAREKH INC.", address: "Ground floor, desai bldg., behind indian bank & surya nursing home, dattatray lane, off. S.v. road, near vijay sales, Santacruz (w)", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400054 },
  { name: "KING'S (MALAD)", address: "1, 2 & 3, GIRNAR APARTMENTS, , S.V. ROAD", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400064 },
  { name: "OSAKA FURNISHING LIMITED - BORIVALI", address: "47, OSAKA HOUSE, NEXT TO POISAR BUS DEPOT, S.V ROAD, BORIVALI (W)", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400092 },
  { name: "INNOVATION LIVING INDIA PRIVATE LIMITED", address: "PLOT NO. 1056-C, 8-2-293/82/A/1056-C, VAMSIRAM'S JYOTHI LORVEN, ROAD NO 45, JUBILEE HILLS, HYDERABAD", city: "HYDERABAD", state: "TELANGANA", pincode: 500033 },
  { name: "DAMASK FABRICS", address: "QU 85 C, , PITAM PURA.", city: "DELHI", state: "DELHI", pincode: 110088 },
  { name: "MAYANK DECOR", address: "FIRST FLOOR, 1-57/32, 33, GACHIBOWLI, RANGA REDDY", city: "HYDERABAD", state: "TELANGANA", pincode: 500081 },
  { name: "HARISONS FURNISHINGS", address: "RING ROAD, AG - 9, , SHALIMAR BAGH.", city: "DELHI", state: "DELHI", pincode: 110052 },
  { name: "RAM FURNISHING", address: "3925/18, KANHAIYA NAGAR, , TRI NAGAR, DELHI", city: "DELHI", state: "DELHI", pincode: 110035 },
  { name: "TATIYA INDUSTRIES", address: "E-4, MARUDHAR INDUSTRIAL AREA, BASNI II PHASE, NEAR MEDIPULSE HOSPITAL", city: "JODHPUR", state: "RAJASTHAN", pincode: 342007 },
  { name: "DECENT FLOOR AND FURNISHING - UDAIPUR", address: "PLOT NO. 4-B, DECENT FLOOR AND FURNISHING, NEAR PARMANAND GARDEN, SHOBHAGPURA, 100 FEET ROAD", city: "UDAIPUR", state: "RAJASTHAN", pincode: 313001 },
  { name: "LEKH RAJ AND SONS", address: "SCF 17, INNER MARKET, SECTOR 7C", city: "CHANDIGARH", state: "CHANDIGARH", pincode: 160019 },
  { name: "M/S TINTS FURNISHINGS", address: "SHOP NO.9, HIRMEN SHOPPING CENTRE, S.V.ROAD, , NEAR CITI CENTRE MALL, GOREGAON (WEST)", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400104 },
  { name: "AESHA SALES CORPORATION", address: "CHANDRA CHOWK, , 1ST LANE, M. J. MARKET", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400002 },
  { name: "BLUEROSE FURNISHINGS LLP", address: "Ground Floor, 391, Parna Kutir, Swami Vivekanand Marg, Opp. Pawan Hans, Vile Parle West", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400056 },
  { name: "AGGARWAL HOME DECOR", address: "SCF 9A/2 BALONGI MAIN ROAD, PHASE 5 SHAHI MAJRA, Mohali, SAS Nagar, Punjab", city: "MOHALI", state: "PUNJAB", pincode: 160059 },
  { name: "INTERIA STYLE CREATIONS LLP", address: "28/2423, B-B5, OPP.CO-OPERATIVE BANK, NELLICODE, THONDAYAD", city: "KOZHIKODE", state: "KERALA", pincode: 673016 },
  { name: "DRAPE SHOPPE - THALTEJ", address: "B BLOCK, DS House, MONDEAL RETAIL PARK, NEAR RAJPATH CLUB, S G ROAD, THALTEJ", city: "AHMEDABAD", state: "GUJARAT", pincode: 380054 },
  { name: "V9 FOAM AND FURNISHING", address: "GF -9, AKSHAT COMPLEX, HIGH TENSION ROAD, SHUBHAN PURA, VADODARA", city: "VADODARA", state: "GUJARAT", pincode: 390023 },
  { name: "GURU RAMDAS FURNISHING ( NEW)", address: "Shop No : 203-204-205, Ashoka Pavilion- A, Opp Kapadia Health Club, Bhatar Road.", city: "SURAT", state: "GUJARAT", pincode: 395002 },
  { name: "FURNISH INDIA", address: "A-261 SANGAM VIHAR OPP.BATRA HOSPITAL, NEAR MUSKAN PROPRTIES.", city: "DELHI", state: "DELHI", pincode: 110062 },
  { name: "SHEETAL FURNISHING - JAIPUR", address: "G-5, NURSURY CIRCLE, VAISHALI NAGAR", city: "JAIPUR", state: "RAJASTHAN", pincode: 302021 },
  { name: "AUM FURNISHING", address: "47, NEW KESHAV NAGAR, , ROOP SAGAR ROAD", city: "UDAIPUR", state: "RAJASTHAN", pincode: 313001 },
  { name: "NEW MAHARAJA FURNISHING", address: "W NO.7, H NO.151/1, NARAYAN PETH", city: "ICHALKARANJI", state: "MAHARASHTRA", pincode: 416115 },
  { name: "DRAPES 'N' MORE FURNISHINGS", address: "8-2-686, 1ST FLOOR, ROAD NO-12, BANJARA HILLS, OPP. TRIUPH SHOWROOM", city: "HYDERABAD", state: "TELANGANA", pincode: 500034 },
  { name: "DRAPE SHOPPE (SURAT) - UNIT - 1", address: "SHREE MAHAVIR TIMBER, 1ST FLOOR, OPP. GANPATI HARDWARE, NEAR CHAR RASTA, UDHNA MAGDALLA ROAD", city: "SURAT", state: "GUJARAT", pincode: 395003 },
  { name: "MARSHALLS ENTERPRISE INDIA PVT. LTD.", address: "PLOT NO. 13, GANDHINAGAR, , OPP. MUNICIPAL INDUSTRIAL ESTATE, DAINIK SHIVNER MARG, WORLI", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400018 },
  { name: "KARUR CURTAINS", address: "2/A-6, RANGAIYAN COMPLEX, PERIYAR NAGAR, KARUR", city: "KARUR", state: "TAMIL NADU", pincode: 639002 },
  { name: "RIDDHI SIDDHI SALES -AHMEDABAD", address: "G-F-F-15, SHAYONA CENTER, MEMCO CHAR RASTA, NARODA ROAD", city: "AHMEDABAD", state: "GUJARAT", pincode: 382330 },
  { name: "M/S DRAPES & SPREADS", address: "G 108, SECTOR 63, NOIDA, , GAUTAM BUDDHA NAGAR", city: "NOIDA", state: "UTTAR PRADESH", pincode: 201301 },
  { name: "KEJALS FURNISHINGS LLP - PUNE", address: "480/A, KUNTE CHOWK, NARAYAN PETH", city: "PUNE", state: "MAHARASHTRA", pincode: 411030 },
  { name: "SHADES - CHENNAI", address: "SHOP NO.1, SULAIMAN ZACKRIA AVENUE, CASA MAJOR ROAD, EGMORE", city: "CHENNAI", state: "TAMIL NADU", pincode: 600008 },
  { name: "RIZA FOAM FURNISHING", address: "103-JC PLAZA, OPP NYAYMANDIR BUS STOP, SABARKANDHA", city: "HIMMATNAGAR", state: "GUJARAT", pincode: 383001 },
  { name: "GALA CURTAIN WORLD", address: "#125, GALA SQUARE, 3RD FLOOR, , RASHTREEYA VIDYALAYA ROAD, VISHVESWARAMPURAM", city: "BANGALORE", state: "KARNATAKA", pincode: 560004 },
  { name: "ARC TECHNOCON PRIVATE LIMITED", address: "3G, LAXMI INDUSTRIAL ESTATE, , LINK ROAD", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400053 },
  { name: "SHREE UMIYA FURNISHING - AHMEDADBAD", address: "3 Aditya Complex, Nr Austmangal Mahadev Temple, Sola Gam Road Science City", city: "AHMEDABAD", state: "GUJARAT", pincode: 380060 },
  { name: "CARPET EMPORIUM - JALANDHAR", address: "GRAND TRUNK ROAD, CARPET EMPORIUM, GRAND TRUNK, JALANDHAR PUNJAB", city: "JALANDHAR", state: "PUNJAB", pincode: 144001 },
  { name: "MAHARASHTRA MATTRESS & FURNISHINGS ( ANDHERI)", address: "GROUND FLOOR, SHOP NO 2, SHRI RAMWADI, JP Road, OPP WADIA HIGH SCHOOL, ANDHERI WEST", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400058 },
  { name: "SRI JAI DURGA FURNISHINGS - VIJAYAWADA", address: "28-36-37, Ammana Estates, , Prakasam road corner, museum road, Governorpet", city: "VIJAYAWADA", state: "ANDHRA PRADESH", pincode: 520002 },
  { name: "NATURAL FURNISHINGS", address: "SHOP NO.4, 5, JAI SAI DARSHAN CHS LTD, OPP.MULJI NAGAR, NEAR VIJAY SALES, S.V.ROAD", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400092 },
  { name: "THE THREADS - AHMEDABAD", address: "C-401, 4TH FLOOR, CELEBRATION CITY CENTER, CHITVAN ROAD, SOUTH BOPAL", city: "AHMEDABAD", state: "GUJARAT", pincode: 380058 },
  { name: "BRAHMANI LEATHER STORES", address: "GROUND FLOOR SHOP NO. 5, PUNIT SHOPPING CENTER, RANAVAV CHOWK", city: "JUNAGADH", state: "GUJARAT", pincode: 362001 },
  { name: "J. R. FURNISHING PVT. LTD. - NEW", address: "B-31-323/448, JAMALPUR AWANA, CHANDIGARH ROAD", city: "LUDHIANA", state: "PUNJAB", pincode: 141010 },
  { name: "IRIS HOMES FURNISHINGS", address: "10/6, POLE NO E395, NAMDHARI CITY, NIHAL VIHAR NELOTHI EXTN, NANGLOI", city: "DELHI", state: "DELHI", pincode: 110041 },
  { name: "INDIA FURNISHING", address: "BEHIND JAIN MANDIR, , NEAR JOSHI SPORTS, NAVI PETH", city: "JALGAON", state: "MAHARASHTRA", pincode: 425001 },
  { name: "VARA - NEW", address: "NO. 1321, FIRST FLOOR, DOUBLE ROAD, , INDIRANAGAR NEAR CAUVERY SCHOOL", city: "BANGALORE", state: "KARNATAKA", pincode: 560038 },
  { name: "DECOREX PRODUCTS INDIA PRIVATE LIMITED - NEW", address: "T-7, OKHLA, , OKHLA INDUSTRIA AREA PHASE II", city: "DELHI", state: "DELHI", pincode: 110020 },
  { name: "GRH DESIGNER CONCEPTS", address: "NO.130 and131, ADINATH NAGAR, NO.50, 200FT ROAD, MADHAVARAM", city: "CHENNAI", state: "TAMIL NADU", pincode: 600060 },
  { name: "R.R. INTERIORS", address: "59, NEW AATISH MARKET, , MANSAROVAR", city: "JAIPUR", state: "RAJASTHAN", pincode: 302020 },
  { name: "LAKSHYA HOME DECOR", address: "122/18, VIJAY PATH, AGARWAL FARM, , MANSAROVAR", city: "JAIPUR", state: "RAJASTHAN", pincode: 302020 },
  { name: "AUDRI", address: "No.699C, 11th Block, 2nd Stage, Nagarabhavi Layout, Nagarabhavi Main Road, Nagarbhavi", city: "BANGALORE", state: "KARNATAKA", pincode: 560072 },
  { name: "RAIFF BY ARODRAPE PRIVATE LIMITED", address: "HOUSE X, MONDEAL BUSINESS PARK, NEAR GURUDWARA, S.G. ROAD", city: "AHMEDABAD", state: "GUJARAT", pincode: 380054 },
  { name: "CHEAP MATTING HOUSE PVT. LTD.", address: "G.T. ROAD, , NEAR JYOTI CHOWK.", city: "JALANDHAR", state: "PUNJAB", pincode: 144001 },
  { name: "CASA FURNISHINGS", address: "214-215, GANPATI TOWER, , LAWRENCE ROAD", city: "AMRITSAR", state: "PUNJAB", pincode: 143001 },
  { name: "PLUM FURNISHING", address: "5-5-39, KRANTI CHOWK, BESIDE HP PETROL PUMP, , JALNA ROAD.", city: "AURANGABAD", state: "MAHARASHTRA", pincode: 431001 },
  { name: "BHAVANI FURNISHINGS", address: "SAGAR VIEW BUILDING, LIBERTY X ROADS, , OPP. M. C. H. BUILDING, DOMALGUDA", city: "SECUNDERABAD", state: "TELANGANA", pincode: 500029 },
  { name: "B PATEL MATTRESSES", address: "SHOP NO .11, SANTOSHI MATA CO.OP. SOC., DR.D.B.MARG, MUMBAI CENTRAL (EAST)", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400008 },
  { name: "CREATIVE WONDERS", address: "PLOT NO- 277, , INDUSTRIAL AREA, PHASE-2", city: "PANCHKULA", state: "HARYANA", pincode: 134113 },
  { name: "S2 FURNISHINGS", address: "#34, B-6, BALFOUR ROAD, , WINDSOR PALACE, KILPAUK STREET", city: "CHENNAI", state: "TAMIL NADU", pincode: 600010 },
  { name: "HUKAMCHAND SOOD & SONS FURNISHING MALL", address: "SAMRALA ROAD, , KHANNA", city: "KHANNA", state: "PUNJAB", pincode: 141401 },
  { name: "DHANUKA ENTERPRISE", address: "Plot No.- Z-370-371 2nd floor, Plot No.- Z-366 TO 369, 1st And 2nd Floor And, , Laxminarayan ndustrial Estate, Udhna Sachin Road, Udhna", city: "SURAT", state: "GUJARAT", pincode: 394210 },
  { name: "WOODLAND FURNISHING", address: "22, CITY MALL, NEAR RAJPATH CLUB, ABOVE OSWAL DINING HALL, S.G.HIGHWAY", city: "AHMEDABAD", state: "GUJARAT", pincode: 380059 },
  { name: "SELECT FURNISHINGS", address: "SF-3, TIME SQUARE ARCADE - 2, NEAR AVALON HOTEL, , OPP. MANN PARTY PLOT, SINDHU BHAVAN ROAD", city: "AHMEDABAD", state: "GUJARAT", pincode: 380054 },
  { name: "ROYAL HANDLOOM", address: "SHOP NO. 528, MAIN BAZAR, , SIRU CHOWK, ULHASNAGAR", city: "MUMBAI", state: "MAHARASHTRA", pincode: 421002 },
  { name: "V. MAYUR", address: "GROUND FLOOR, 107, ANAJBAJAR CO OP HOUSING SOCIETY, BEHIND GAYATRI DAIRY, KHOKHRA", city: "AHMEDABAD", state: "GUJARAT", pincode: 380008 },
  { name: "ART FURNISHING", address: "GROUND FLOOR, SHOP NO. 2, RUPESH HEIGHTS, Datta Mandir Road, India Oil Petrol Pump, Wakad, Pimpri Chinchwad", city: "PUNE", state: "MAHARASHTRA", pincode: 411057 },
  { name: "DRAPES AVENUE --", address: "279/288, AMAR JYOTHI LAYOUT, , INTERMEDIATE RING ROAD.", city: "BANGALORE", state: "KARNATAKA", pincode: 560071 },
  { name: "NAVKAR FURNISHING - MUMBAI", address: "SHOP NO.4, PLOT NO.226, SHRI VINAYAK CHS, SEC. 5, DR.B.A.ROAD, CHARKOP, KANDIVALI W", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400067 },
  { name: "KING DRAPE", address: "NO.25, RAM THULSI CHAMBERS, , M S RAMAIAH ROAD, MATHIKERE, BENGALURU URBAN", city: "BANGALORE", state: "KARNATAKA", pincode: 560054 },
  { name: "SPACIYOUS", address: "NO. 6, NEW TIMBER YARD, MYSORE ROAD", city: "BANGALORE", state: "KARNATAKA", pincode: 560026 },
  { name: "THAR LIFESTYLE PVT. LTD", address: "30, GOLE BUILDING ROAD, , JALORI GATE", city: "JODHPUR", state: "RAJASTHAN", pincode: 342003 },
  { name: "DHRUV FURNISHINGS & FLOORING", address: "H.B. 8/ 8, NEAR ARYA SAMAJ, , PIMPRI COLONY.", city: "PUNE", state: "MAHARASHTRA", pincode: 411017 },
  { name: "PALETTE", address: "PLOT NO.1, SHOP NO. 1, SHRI NIKETAN COLONY, , NR. COSMOS BANK, JALNA ROAD", city: "AURANGABAD", state: "MAHARASHTRA", pincode: 431001 },
  { name: "NEO FABRIQUE FURNISHINGS", address: "PLOT NO-21 & 22, TRENDZ DWARAKA, , , NEAR TELECOM NAGAR BUS STOP, GACCHIBOWLI.", city: "HYDERABAD", state: "TELANGANA", pincode: 500032 },
  { name: "SILK SAJAWAT", address: "RAMKRISHNA NAGAR, , MAIN ROAD.", city: "RAJKOT", state: "GUJARAT", pincode: 360002 },
  { name: "N.K. CURTAIN", address: "GR. FLOOR, 17/1457, ZAK TOWER NEAR KALYAN KENDRA, CHINTHAVALAPPU RAM MOHAN ROAD CALICUT-4", city: "CALICUT", state: "KERALA", pincode: 673004 },
  { name: "DREAM DECOR - MUMBAI", address: "SHOP NO 103, CRESENT MANSION, OPP. GAMDEVI POLICE STATION, NANA CHOWK, GRANT ROAD", city: "MUMBAI", state: "MAHARASHTRA", pincode: 400007 },
  { name: "GAGAN HANDLOOM", address: "SCO - 5, , SECTOR - 11", city: "PANCHKULA", state: "HARYANA", pincode: 133302 },
];

/** Store count per state, derived once rather than recomputed per render. */
export const STORE_COUNTS: Record<string, number> = STORES.reduce<Record<string, number>>(
  (acc, s) => ((acc[s.state] = (acc[s.state] ?? 0) + 1), acc),
  {}
);

/** States that actually have a stockist, biggest first. */
export const STORE_STATES = Object.keys(STORE_COUNTS).sort(
  (a, b) => STORE_COUNTS[b] - STORE_COUNTS[a] || a.localeCompare(b)
);
